### ISSUE TITLE
TypeError: jodit__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor

### ISSUE THREAD

**Issue by ChunAllen** [WendellAdriel/jodit-vue#12] opened 2020-07-08 10:51 UTC
I'm currently using `jodit-vue@1.3.0`

then in my `vue-editor.js`
```
import 'jodit/build/jodit.min.css'
import Vue from 'vue'
import JoditVue from 'jodit-vue'

Vue.component('jodit-vue', JoditVue)
```

and I import this in my **main.js** file

in my **BaseEditor.vue**
```
<jodit-vue v-model="content" />

 export default {
    name: 'BaseEditor',
    data() {
      return {
        content: "Hello"
      }
    }
}
```

but when I check the browser console, I'm getting 
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: jodit__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor"

```

**Comment by Ruslan-F** [comment] 2020-07-14 08:04
@WendellAdriel any ETA / plans to fix this one..? Looks like major bug, breaking whole package. Parent library was update almost month ago. Thanks.

**Comment by WendellAdriel** [comment] 2020-07-14 09:34
Hello, @ChunAllen and @Ruslan-F 
Sorry for the delay.

Can you please help me to simulate this issue? Can you create a live example?

I created a CodeSandbox with jodit-vue@1.3.0 to try to simulate it, but I was unable to do so:
https://codesandbox.io/s/youthful-meadow-qlnd2

**Comment by Ruslan-F** [comment] 2020-07-14 11:18
@WendellAdriel thanks for quick response.
Reproduction link:
https://codesandbox.io/s/gallant-hypatia-mccw7?file=/package.json

Not identical error, but with same point - `TypeError: (0 , Jodit.default) is not a constructor`.
Btw, I got this bug with:
```
"jodit-vue": "2.2.0",
"vue": "^2.6.11"
```

**Comment by WendellAdriel** [comment] 2020-07-16 11:20
@ChunAllen and @Ruslan-F sorry for the delay again
I just released a new version: 2.2.1, can you please try it and if it's ok, can you close the issue?
Thank you so much.

**Comment by Ruslan-F** [comment] 2020-07-16 11:42
@WendellAdriel works now. Thank you.

**Comment by WendellAdriel** [comment] 2020-07-16 11:47
You're welcome, if any of you @ChunAllen and @Ruslan-F wants to be added to the all contributors list, please create a PR adding your user to the list with the "Bug Report" option.

**Closed as completed** 2020-07-16 11:48 UTC
