### ISSUE TITLE
Clearing cell in table from popup menu actions is not working

### ISSUE THREAD

**Issue by kkolataj** [WendellAdriel/jodit-vue#22] opened 2021-03-24 13:36 UTC
Package.json content:
{
  "name": "wysig",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "jodit-vue": "^2.3.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by WendellAdriel** [comment] 2021-03-24 15:00
Hello, @kkolataj.
Before continuing to investigate I need to check two things:
- Did you test it with Jodit Editor itself (without our wrapper)? Because if the issue is with the Editor itself, you should create an issue on the Editor repository instead.

If you did that and the issue is with the wrapper, can you please share an example of the issue (repository or Codesandbox or anything like this), please?

**Comment by kkolataj** [comment] 2021-03-24 15:17
@WendellAdriel as i see, problem is also in newest version of jodit itself, there is an example to test:
https://codepen.io/claudioCODE/pen/rNjVPeK
maybe thaths why in jodit-vue version is not working, which version could i use for workaround?

**Comment by WendellAdriel** [comment] 2021-03-24 15:31
@kkolataj you can check in their repository if they already have that issue open, if not you can open it.
AS a workaround you can try to use jodit-vue 2.2 or even 2.1 that are using older jodit versions.

**Comment by kkolataj** [comment] 2021-03-24 16:24
@WendellAdriel downgrade jodit-vue to 2.2.1 version fixed issue. I dont want to close this ticket because its only workaround.

**Comment by WendellAdriel** [comment] 2021-03-25 10:00
I'm glad that it worked @kkolataj.
I'm going to close this issue since the error is within the editor itself and not the wrapper.

**Closed as completed by WendellAdriel** 2021-03-25 10:00 UTC
